// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: pb/remote_exec.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobDetails_Status int32

const (
	JobDetails_RUNNING   JobDetails_Status = 0
	JobDetails_COMPLETED JobDetails_Status = 1
	JobDetails_ERRORED   JobDetails_Status = 2
	JobDetails_STOPPED   JobDetails_Status = 3
)

// Enum value maps for JobDetails_Status.
var (
	JobDetails_Status_name = map[int32]string{
		0: "RUNNING",
		1: "COMPLETED",
		2: "ERRORED",
		3: "STOPPED",
	}
	JobDetails_Status_value = map[string]int32{
		"RUNNING":   0,
		"COMPLETED": 1,
		"ERRORED":   2,
		"STOPPED":   3,
	}
)

func (x JobDetails_Status) Enum() *JobDetails_Status {
	p := new(JobDetails_Status)
	*p = x
	return p
}

func (x JobDetails_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobDetails_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_remote_exec_proto_enumTypes[0].Descriptor()
}

func (JobDetails_Status) Type() protoreflect.EnumType {
	return &file_pb_remote_exec_proto_enumTypes[0]
}

func (x JobDetails_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobDetails_Status.Descriptor instead.
func (JobDetails_Status) EnumDescriptor() ([]byte, []int) {
	return file_pb_remote_exec_proto_rawDescGZIP(), []int{2, 0}
}

// The request message containing the command
type CmdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Arguments     []string               `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CmdRequest) Reset() {
	*x = CmdRequest{}
	mi := &file_pb_remote_exec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CmdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CmdRequest) ProtoMessage() {}

func (x *CmdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_remote_exec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CmdRequest.ProtoReflect.Descriptor instead.
func (*CmdRequest) Descriptor() ([]byte, []int) {
	return file_pb_remote_exec_proto_rawDescGZIP(), []int{0}
}

func (x *CmdRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CmdRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// The request for a Job status
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_pb_remote_exec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_remote_exec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_pb_remote_exec_proto_rawDescGZIP(), []int{1}
}

func (x *GetRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

// The status for a Get Job
type JobDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobDetails_Status      `protobuf:"varint,2,opt,name=status,proto3,enum=JobDetails_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDetails) Reset() {
	*x = JobDetails{}
	mi := &file_pb_remote_exec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetails) ProtoMessage() {}

func (x *JobDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pb_remote_exec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetails.ProtoReflect.Descriptor instead.
func (*JobDetails) Descriptor() ([]byte, []int) {
	return file_pb_remote_exec_proto_rawDescGZIP(), []int{2}
}

func (x *JobDetails) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobDetails) GetStatus() JobDetails_Status {
	if x != nil {
		return x.Status
	}
	return JobDetails_RUNNING
}

// The response for a Get Job, with the combined output from stdout and stderr
type JobOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        []byte                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOutput) Reset() {
	*x = JobOutput{}
	mi := &file_pb_remote_exec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOutput) ProtoMessage() {}

func (x *JobOutput) ProtoReflect() protoreflect.Message {
	mi := &file_pb_remote_exec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOutput.ProtoReflect.Descriptor instead.
func (*JobOutput) Descriptor() ([]byte, []int) {
	return file_pb_remote_exec_proto_rawDescGZIP(), []int{3}
}

func (x *JobOutput) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

// The request for a Stop operation containing the job id
type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_pb_remote_exec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_remote_exec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_pb_remote_exec_proto_rawDescGZIP(), []int{4}
}

func (x *StopRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

var File_pb_remote_exec_proto protoreflect.FileDescriptor

const file_pb_remote_exec_proto_rawDesc = "" +
	"\n" +
	"\x14pb/remote_exec.proto\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\n" +
	"CmdRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1c\n" +
	"\targuments\x18\x02 \x03(\tR\targuments\"#\n" +
	"\n" +
	"GetRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x8f\x01\n" +
	"\n" +
	"JobDetails\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.JobDetails.StatusR\x06status\">\n" +
	"\x06Status\x12\v\n" +
	"\aRUNNING\x10\x00\x12\r\n" +
	"\tCOMPLETED\x10\x01\x12\v\n" +
	"\aERRORED\x10\x02\x12\v\n" +
	"\aSTOPPED\x10\x03\"#\n" +
	"\tJobOutput\x12\x16\n" +
	"\x06output\x18\x01 \x01(\fR\x06output\"$\n" +
	"\vStopRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId2\xc1\x01\n" +
	"\x0eRemoteExecutor\x12)\n" +
	"\vExecCommand\x12\v.CmdRequest\x1a\v.JobDetails\"\x00\x12'\n" +
	"\tGetStatus\x12\v.GetRequest\x1a\v.JobDetails\"\x00\x12(\n" +
	"\tGetOutput\x12\v.GetRequest\x1a\n" +
	".JobOutput\"\x000\x01\x121\n" +
	"\aStopJob\x12\f.StopRequest\x1a\x16.google.protobuf.Empty\"\x00B\x06Z\x04.;pbb\x06proto3"

var (
	file_pb_remote_exec_proto_rawDescOnce sync.Once
	file_pb_remote_exec_proto_rawDescData []byte
)

func file_pb_remote_exec_proto_rawDescGZIP() []byte {
	file_pb_remote_exec_proto_rawDescOnce.Do(func() {
		file_pb_remote_exec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_remote_exec_proto_rawDesc), len(file_pb_remote_exec_proto_rawDesc)))
	})
	return file_pb_remote_exec_proto_rawDescData
}

var file_pb_remote_exec_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_remote_exec_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_remote_exec_proto_goTypes = []any{
	(JobDetails_Status)(0), // 0: JobDetails.Status
	(*CmdRequest)(nil),     // 1: CmdRequest
	(*GetRequest)(nil),     // 2: GetRequest
	(*JobDetails)(nil),     // 3: JobDetails
	(*JobOutput)(nil),      // 4: JobOutput
	(*StopRequest)(nil),    // 5: StopRequest
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_pb_remote_exec_proto_depIdxs = []int32{
	0, // 0: JobDetails.status:type_name -> JobDetails.Status
	1, // 1: RemoteExecutor.ExecCommand:input_type -> CmdRequest
	2, // 2: RemoteExecutor.GetStatus:input_type -> GetRequest
	2, // 3: RemoteExecutor.GetOutput:input_type -> GetRequest
	5, // 4: RemoteExecutor.StopJob:input_type -> StopRequest
	3, // 5: RemoteExecutor.ExecCommand:output_type -> JobDetails
	3, // 6: RemoteExecutor.GetStatus:output_type -> JobDetails
	4, // 7: RemoteExecutor.GetOutput:output_type -> JobOutput
	6, // 8: RemoteExecutor.StopJob:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_remote_exec_proto_init() }
func file_pb_remote_exec_proto_init() {
	if File_pb_remote_exec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_remote_exec_proto_rawDesc), len(file_pb_remote_exec_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_remote_exec_proto_goTypes,
		DependencyIndexes: file_pb_remote_exec_proto_depIdxs,
		EnumInfos:         file_pb_remote_exec_proto_enumTypes,
		MessageInfos:      file_pb_remote_exec_proto_msgTypes,
	}.Build()
	File_pb_remote_exec_proto = out.File
	file_pb_remote_exec_proto_goTypes = nil
	file_pb_remote_exec_proto_depIdxs = nil
}
